package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatorproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorProduct.IndicatorProductID
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    private Integer indicatorproductid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorProduct.Points
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    private BigDecimal points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorProduct.IndicatorProductID
     *
     * @return the value of PER_IndicatorProduct.IndicatorProductID
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    public Integer getIndicatorproductid() {
        return indicatorproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorProduct.IndicatorProductID
     *
     * @param indicatorproductid the value for PER_IndicatorProduct.IndicatorProductID
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    public void setIndicatorproductid(Integer indicatorproductid) {
        this.indicatorproductid = indicatorproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorProduct.Points
     *
     * @return the value of PER_IndicatorProduct.Points
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorProduct.Points
     *
     * @param points the value for PER_IndicatorProduct.Points
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
}