package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatorappraisal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorAppraisal.IndicatorAppraisalID
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    private Integer indicatorappraisalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorAppraisal.Points
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    private BigDecimal points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorAppraisal.IndicatorAppraisalID
     *
     * @return the value of PER_IndicatorAppraisal.IndicatorAppraisalID
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    public Integer getIndicatorappraisalid() {
        return indicatorappraisalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorAppraisal.IndicatorAppraisalID
     *
     * @param indicatorappraisalid the value for PER_IndicatorAppraisal.IndicatorAppraisalID
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    public void setIndicatorappraisalid(Integer indicatorappraisalid) {
        this.indicatorappraisalid = indicatorappraisalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorAppraisal.Points
     *
     * @return the value of PER_IndicatorAppraisal.Points
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorAppraisal.Points
     *
     * @param points the value for PER_IndicatorAppraisal.Points
     *
     * @mbg.generated Sun Mar 14 20:58:03 CST 2021
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
}