package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatortech {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorTech.IndicatorTechID
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    private Integer indicatortechid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorTech.Points
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    private BigDecimal points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorTech.IndicatorTechID
     *
     * @return the value of PER_IndicatorTech.IndicatorTechID
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    public Integer getIndicatortechid() {
        return indicatortechid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorTech.IndicatorTechID
     *
     * @param indicatortechid the value for PER_IndicatorTech.IndicatorTechID
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    public void setIndicatortechid(Integer indicatortechid) {
        this.indicatortechid = indicatortechid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorTech.Points
     *
     * @return the value of PER_IndicatorTech.Points
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorTech.Points
     *
     * @param points the value for PER_IndicatorTech.Points
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
}