package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatorstandard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorStandard.IndicatorStandardID
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    private Integer indicatorstandardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorStandard.Points
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    private BigDecimal points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorStandard.IndicatorStandardID
     *
     * @return the value of PER_IndicatorStandard.IndicatorStandardID
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    public Integer getIndicatorstandardid() {
        return indicatorstandardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorStandard.IndicatorStandardID
     *
     * @param indicatorstandardid the value for PER_IndicatorStandard.IndicatorStandardID
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    public void setIndicatorstandardid(Integer indicatorstandardid) {
        this.indicatorstandardid = indicatorstandardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorStandard.Points
     *
     * @return the value of PER_IndicatorStandard.Points
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorStandard.Points
     *
     * @param points the value for PER_IndicatorStandard.Points
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
}