package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIncome {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.IncomeID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private Integer incomeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.TeamID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private Integer teamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.Year
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.ProjectName
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private String projectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.ProjectCode
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private String projectcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.ManagerID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.Period
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.ContractMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private BigDecimal contractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.ThisYearMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private BigDecimal thisyearmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.Type
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_Income.Status
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.IncomeID
     *
     * @return the value of PER_Income.IncomeID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public Integer getIncomeid() {
        return incomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.IncomeID
     *
     * @param incomeid the value for PER_Income.IncomeID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setIncomeid(Integer incomeid) {
        this.incomeid = incomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.TeamID
     *
     * @return the value of PER_Income.TeamID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public Integer getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.TeamID
     *
     * @param teamid the value for PER_Income.TeamID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.Year
     *
     * @return the value of PER_Income.Year
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.Year
     *
     * @param year the value for PER_Income.Year
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.ProjectName
     *
     * @return the value of PER_Income.ProjectName
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.ProjectName
     *
     * @param projectname the value for PER_Income.ProjectName
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.ProjectCode
     *
     * @return the value of PER_Income.ProjectCode
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public String getProjectcode() {
        return projectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.ProjectCode
     *
     * @param projectcode the value for PER_Income.ProjectCode
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.ManagerID
     *
     * @return the value of PER_Income.ManagerID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.ManagerID
     *
     * @param managerid the value for PER_Income.ManagerID
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.Period
     *
     * @return the value of PER_Income.Period
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.Period
     *
     * @param period the value for PER_Income.Period
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.ContractMoney
     *
     * @return the value of PER_Income.ContractMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public BigDecimal getContractmoney() {
        return contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.ContractMoney
     *
     * @param contractmoney the value for PER_Income.ContractMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setContractmoney(BigDecimal contractmoney) {
        this.contractmoney = contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.ThisYearMoney
     *
     * @return the value of PER_Income.ThisYearMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public BigDecimal getThisyearmoney() {
        return thisyearmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.ThisYearMoney
     *
     * @param thisyearmoney the value for PER_Income.ThisYearMoney
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setThisyearmoney(BigDecimal thisyearmoney) {
        this.thisyearmoney = thisyearmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.Type
     *
     * @return the value of PER_Income.Type
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.Type
     *
     * @param type the value for PER_Income.Type
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_Income.Status
     *
     * @return the value of PER_Income.Status
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_Income.Status
     *
     * @param status the value for PER_Income.Status
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }
}