package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatorarticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorArticle.IndicatorArticleID
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    private Integer indicatorarticleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorArticle.Points
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    private BigDecimal points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorArticle.IndicatorArticleID
     *
     * @return the value of PER_IndicatorArticle.IndicatorArticleID
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    public Integer getIndicatorarticleid() {
        return indicatorarticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorArticle.IndicatorArticleID
     *
     * @param indicatorarticleid the value for PER_IndicatorArticle.IndicatorArticleID
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    public void setIndicatorarticleid(Integer indicatorarticleid) {
        this.indicatorarticleid = indicatorarticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorArticle.Points
     *
     * @return the value of PER_IndicatorArticle.Points
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorArticle.Points
     *
     * @param points the value for PER_IndicatorArticle.Points
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
}