package com.ruoyi.performance.domain;

import java.math.BigDecimal;

public class PerIndicatororderrate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorOrderRate.IndicatorOrderRateID
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    private Integer indicatororderrateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorOrderRate.AuthorOrder
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    private String authororder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PER_IndicatorOrderRate.Rate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    private BigDecimal rate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorOrderRate.IndicatorOrderRateID
     *
     * @return the value of PER_IndicatorOrderRate.IndicatorOrderRateID
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public Integer getIndicatororderrateid() {
        return indicatororderrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorOrderRate.IndicatorOrderRateID
     *
     * @param indicatororderrateid the value for PER_IndicatorOrderRate.IndicatorOrderRateID
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public void setIndicatororderrateid(Integer indicatororderrateid) {
        this.indicatororderrateid = indicatororderrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorOrderRate.AuthorOrder
     *
     * @return the value of PER_IndicatorOrderRate.AuthorOrder
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public String getAuthororder() {
        return authororder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorOrderRate.AuthorOrder
     *
     * @param authororder the value for PER_IndicatorOrderRate.AuthorOrder
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public void setAuthororder(String authororder) {
        this.authororder = authororder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PER_IndicatorOrderRate.Rate
     *
     * @return the value of PER_IndicatorOrderRate.Rate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PER_IndicatorOrderRate.Rate
     *
     * @param rate the value for PER_IndicatorOrderRate.Rate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }
}