package com.ruoyi.sku.domain;

import java.util.Date;

public class SkuExport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.export_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Long exportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.user_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.export_time
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Date exportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.sku_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.photo_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Long photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.status
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_export.export_path
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    private String exportPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.export_id
     *
     * @return the value of sku_export.export_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Long getExportId() {
        return exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.export_id
     *
     * @param exportId the value for sku_export.export_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setExportId(Long exportId) {
        this.exportId = exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.user_id
     *
     * @return the value of sku_export.user_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.user_id
     *
     * @param userId the value for sku_export.user_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.export_time
     *
     * @return the value of sku_export.export_time
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Date getExportTime() {
        return exportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.export_time
     *
     * @param exportTime the value for sku_export.export_time
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setExportTime(Date exportTime) {
        this.exportTime = exportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.sku_id
     *
     * @return the value of sku_export.sku_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.sku_id
     *
     * @param skuId the value for sku_export.sku_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.photo_id
     *
     * @return the value of sku_export.photo_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.photo_id
     *
     * @param photoId the value for sku_export.photo_id
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.status
     *
     * @return the value of sku_export.status
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.status
     *
     * @param status the value for sku_export.status
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_export.export_path
     *
     * @return the value of sku_export.export_path
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public String getExportPath() {
        return exportPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_export.export_path
     *
     * @param exportPath the value for sku_export.export_path
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    public void setExportPath(String exportPath) {
        this.exportPath = exportPath;
    }
}