package com.ruoyi.contract.domain;

import java.math.BigDecimal;

public class AudContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer contractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractCode
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String contractcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractName
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String contractname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractType
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer contracttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer contractuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String contracttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ProjectID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.OrganizationID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer organizationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.ContractMoney
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private BigDecimal contractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.daxie
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String daxie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.SupplierID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer supplierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.PayTotalTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer paytotaltimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.PayedTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer payedtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.Reason
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.PassTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String passtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.SignConfirmTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String signconfirmtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.SignConfirmUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer signconfirmuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.FirstPayTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private String firstpaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Contract.SheetStatus
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    private Integer sheetstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractID
     *
     * @return the value of Aud_Contract.ContractID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractID
     *
     * @param contractid the value for Aud_Contract.ContractID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContractid(Integer contractid) {
        this.contractid = contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractCode
     *
     * @return the value of Aud_Contract.ContractCode
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getContractcode() {
        return contractcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractCode
     *
     * @param contractcode the value for Aud_Contract.ContractCode
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContractcode(String contractcode) {
        this.contractcode = contractcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractName
     *
     * @return the value of Aud_Contract.ContractName
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getContractname() {
        return contractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractName
     *
     * @param contractname the value for Aud_Contract.ContractName
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContractname(String contractname) {
        this.contractname = contractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractType
     *
     * @return the value of Aud_Contract.ContractType
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getContracttype() {
        return contracttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractType
     *
     * @param contracttype the value for Aud_Contract.ContractType
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContracttype(Integer contracttype) {
        this.contracttype = contracttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractUserID
     *
     * @return the value of Aud_Contract.ContractUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getContractuserid() {
        return contractuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractUserID
     *
     * @param contractuserid the value for Aud_Contract.ContractUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContractuserid(Integer contractuserid) {
        this.contractuserid = contractuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractTime
     *
     * @return the value of Aud_Contract.ContractTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getContracttime() {
        return contracttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractTime
     *
     * @param contracttime the value for Aud_Contract.ContractTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContracttime(String contracttime) {
        this.contracttime = contracttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ProjectID
     *
     * @return the value of Aud_Contract.ProjectID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ProjectID
     *
     * @param projectid the value for Aud_Contract.ProjectID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.OrganizationID
     *
     * @return the value of Aud_Contract.OrganizationID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.OrganizationID
     *
     * @param organizationid the value for Aud_Contract.OrganizationID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setOrganizationid(Integer organizationid) {
        this.organizationid = organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.ContractMoney
     *
     * @return the value of Aud_Contract.ContractMoney
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public BigDecimal getContractmoney() {
        return contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.ContractMoney
     *
     * @param contractmoney the value for Aud_Contract.ContractMoney
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setContractmoney(BigDecimal contractmoney) {
        this.contractmoney = contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.daxie
     *
     * @return the value of Aud_Contract.daxie
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getDaxie() {
        return daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.daxie
     *
     * @param daxie the value for Aud_Contract.daxie
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setDaxie(String daxie) {
        this.daxie = daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.SupplierID
     *
     * @return the value of Aud_Contract.SupplierID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.SupplierID
     *
     * @param supplierid the value for Aud_Contract.SupplierID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.PayTotalTimes
     *
     * @return the value of Aud_Contract.PayTotalTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getPaytotaltimes() {
        return paytotaltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.PayTotalTimes
     *
     * @param paytotaltimes the value for Aud_Contract.PayTotalTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setPaytotaltimes(Integer paytotaltimes) {
        this.paytotaltimes = paytotaltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.PayedTimes
     *
     * @return the value of Aud_Contract.PayedTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getPayedtimes() {
        return payedtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.PayedTimes
     *
     * @param payedtimes the value for Aud_Contract.PayedTimes
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setPayedtimes(Integer payedtimes) {
        this.payedtimes = payedtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.Reason
     *
     * @return the value of Aud_Contract.Reason
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.Reason
     *
     * @param reason the value for Aud_Contract.Reason
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.PassTime
     *
     * @return the value of Aud_Contract.PassTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getPasstime() {
        return passtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.PassTime
     *
     * @param passtime the value for Aud_Contract.PassTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setPasstime(String passtime) {
        this.passtime = passtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.SignConfirmTime
     *
     * @return the value of Aud_Contract.SignConfirmTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getSignconfirmtime() {
        return signconfirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.SignConfirmTime
     *
     * @param signconfirmtime the value for Aud_Contract.SignConfirmTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setSignconfirmtime(String signconfirmtime) {
        this.signconfirmtime = signconfirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.SignConfirmUserID
     *
     * @return the value of Aud_Contract.SignConfirmUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getSignconfirmuserid() {
        return signconfirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.SignConfirmUserID
     *
     * @param signconfirmuserid the value for Aud_Contract.SignConfirmUserID
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setSignconfirmuserid(Integer signconfirmuserid) {
        this.signconfirmuserid = signconfirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.FirstPayTime
     *
     * @return the value of Aud_Contract.FirstPayTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public String getFirstpaytime() {
        return firstpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.FirstPayTime
     *
     * @param firstpaytime the value for Aud_Contract.FirstPayTime
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setFirstpaytime(String firstpaytime) {
        this.firstpaytime = firstpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Contract.SheetStatus
     *
     * @return the value of Aud_Contract.SheetStatus
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public Integer getSheetstatus() {
        return sheetstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Contract.SheetStatus
     *
     * @param sheetstatus the value for Aud_Contract.SheetStatus
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    public void setSheetstatus(Integer sheetstatus) {
        this.sheetstatus = sheetstatus;
    }
}