package com.ruoyi.api.domain;

public class AppClientinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column App_ClientInfo.ClientID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column App_ClientInfo.UserID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column App_ClientInfo.ClientID
     *
     * @return the value of App_ClientInfo.ClientID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column App_ClientInfo.ClientID
     *
     * @param clientid the value for App_ClientInfo.ClientID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column App_ClientInfo.UserID
     *
     * @return the value of App_ClientInfo.UserID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column App_ClientInfo.UserID
     *
     * @param userid the value for App_ClientInfo.UserID
     *
     * @mbg.generated Wed Feb 17 23:45:36 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}