package com.ruoyi.contract.mapper;

import com.ruoyi.contract.domain.AudContract;
import java.util.List;

public interface AudContractMapper {

    List<AudContract> selectContractTijiaoren(AudContract record);

    int deleteByPrimaryKey(Integer contractid);

    int insert(AudContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Contract
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    AudContract selectByPrimaryKey(Integer contractid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Contract
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    List<AudContract> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Contract
     *
     * @mbg.generated Sun Feb 21 21:31:38 CST 2021
     */
    int updateByPrimaryKey(AudContract record);
}