package com.ruoyi.achieve.mapper;

import com.ruoyi.achieve.domain.AchArticle;
import java.util.List;

public interface AchArticleMapper {

    List<AchArticle> selectAchArticle(AchArticle record);
    AchArticle selectAchArticleById(Integer articleid);

    int deleteByPrimaryKey(Integer articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Article
     *
     * @mbg.generated Mon Mar 15 13:12:26 CST 2021
     */
    int insert(AchArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Article
     *
     * @mbg.generated Mon Mar 15 13:12:26 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Article
     *
     * @mbg.generated Mon Mar 15 13:12:26 CST 2021
     */
    List<AchArticle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Article
     *
     * @mbg.generated Mon Mar 15 13:12:26 CST 2021
     */
    int updateByPrimaryKey(AchArticle record);
}