package com.ruoyi.achieve.mapper;

import com.ruoyi.achieve.domain.AchAppraisal;
import java.util.List;

public interface AchAppraisalMapper {

    List<AchAppraisal> selectAchAppraisal(AchAppraisal record);


    AchAppraisal selectAchAppraisalById(Integer appraisalid);

    int deleteByPrimaryKey(Integer appraisalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Appraisal
     *
     * @mbg.generated Mon Mar 15 13:51:06 CST 2021
     */
    int insert(AchAppraisal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Appraisal
     *
     * @mbg.generated Mon Mar 15 13:51:06 CST 2021
     */
    AchAppraisal selectByPrimaryKey(Integer appraisalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Appraisal
     *
     * @mbg.generated Mon Mar 15 13:51:06 CST 2021
     */
    List<AchAppraisal> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Appraisal
     *
     * @mbg.generated Mon Mar 15 13:51:06 CST 2021
     */
    int updateByPrimaryKey(AchAppraisal record);
}