package com.ruoyi.achieve.mapper;

import com.ruoyi.achieve.domain.AchProduct;
import java.util.List;

public interface AchProductMapper {

    List<AchProduct> selectAchProduct(AchProduct record);


    int deleteByPrimaryKey(Integer productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Product
     *
     * @mbg.generated Mon Mar 15 13:50:00 CST 2021
     */
    int insert(AchProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Product
     *
     * @mbg.generated Mon Mar 15 13:50:00 CST 2021
     */
    AchProduct selectByPrimaryKey(Integer productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Product
     *
     * @mbg.generated Mon Mar 15 13:50:00 CST 2021
     */
    List<AchProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Product
     *
     * @mbg.generated Mon Mar 15 13:50:00 CST 2021
     */
    int updateByPrimaryKey(AchProduct record);
}