package com.ruoyi.achieve.mapper;

import com.ruoyi.achieve.domain.AchStandard;
import java.util.List;

public interface AchStandardMapper {

    List<AchStandard> selectAchStandard(AchStandard record);

    int deleteByPrimaryKey(Integer standardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Standard
     *
     * @mbg.generated Mon Mar 15 12:19:38 CST 2021
     */
    int insert(AchStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Standard
     *
     * @mbg.generated Mon Mar 15 12:19:38 CST 2021
     */
    AchStandard selectByPrimaryKey(Integer standardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Standard
     *
     * @mbg.generated Mon Mar 15 12:19:38 CST 2021
     */
    List<AchStandard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Standard
     *
     * @mbg.generated Mon Mar 15 12:19:38 CST 2021
     */
    int updateByPrimaryKey(AchStandard record);
}