package com.ruoyi.achieve.mapper;

import com.ruoyi.achieve.domain.AchAppraisal;
import com.ruoyi.achieve.domain.AchTech;
import java.util.List;

public interface AchTechMapper {
    List<AchTech> selectAchTech(AchTech record);
    AchTech selectAchTechById(Integer techid);

    
    int deleteByPrimaryKey(Integer techid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Tech
     *
     * @mbg.generated Mon Mar 15 13:54:13 CST 2021
     */
    int insert(AchTech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Tech
     *
     * @mbg.generated Mon Mar 15 13:54:13 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Tech
     *
     * @mbg.generated Mon Mar 15 13:54:13 CST 2021
     */
    List<AchTech> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACH_Tech
     *
     * @mbg.generated Mon Mar 15 13:54:13 CST 2021
     */
    int updateByPrimaryKey(AchTech record);
}