package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerAddscoreapply;
import java.util.List;

public interface PerAddscoreapplyMapper {

    List<PerAddscoreapply> selectPerAddscoreapply(PerAddscoreapply record);

    PerAddscoreapply selectPerAddscoreapplyById(Integer applyid);

    int insertPerAddscoreapply(PerAddscoreapply record);
    int updatePerAddscoreapply(PerAddscoreapply record);

    int updatePerAddscoreapplyDeletedById(Integer applyid);
    //
    int updatePerAddscoreapplyConfirm(PerAddscoreapply record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */

    PerAddscoreapply selectByPrimaryKey(Integer applyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */
    List<PerAddscoreapply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */

}