package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerAddscoreapply;
import java.util.List;

public interface PerAddscoreapplyMapper {

    List<PerAddscoreapply> selectPerAddscoreapply(PerAddscoreapply record);

    int deleteByPrimaryKey(Integer applyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */
    int insert(PerAddscoreapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */
    PerAddscoreapply selectByPrimaryKey(Integer applyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */
    List<PerAddscoreapply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_AddScoreApply
     *
     * @mbg.generated Tue Mar 23 09:30:21 CST 2021
     */
    int updateByPrimaryKey(PerAddscoreapply record);
}