package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerConfirmqequest;
import java.util.List;

public interface PerConfirmqequestMapper {

    List<PerConfirmqequest> selectPerConfirmRequest(PerConfirmqequest record);

    int insertPerConfirmqequest(PerConfirmqequest record);


    int updatePerConfirmqequestByTeamYear(PerConfirmqequest record);


    int updatePerConfirmqequest(PerConfirmqequest record);


    int deleteByPrimaryKey(Integer requestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ConfirmQequest
     *
     * @mbg.generated Tue Mar 16 09:32:30 CST 2021
     */
    PerConfirmqequest selectByPrimaryKey(Integer requestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ConfirmQequest
     *
     * @mbg.generated Tue Mar 16 09:32:30 CST 2021
     */
    List<PerConfirmqequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ConfirmQequest
     *
     * @mbg.generated Tue Mar 16 09:32:30 CST 2021
     */

}