package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorprize;
import java.util.List;

public interface PerIndicatorprizeMapper {

    List<PerIndicatorprize> selectPerIndicatorprize(PerIndicatorprize record);

    PerIndicatorprize selectPerIndicatorprizeById(Integer indicatorprizeid);

    int insertPerIndicatorprize(PerIndicatorprize record);
    int updatePerIndicatorprize(PerIndicatorprize record);
    int updatePerIndicatorprizeIfDeleted(PerIndicatorprize record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPrize
     *
     * @mbg.generated Sun Mar 14 07:52:10 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatorprizeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPrize
     *
     * @mbg.generated Sun Mar 14 07:52:10 CST 2021
     */
    int insert(PerIndicatorprize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPrize
     *
     * @mbg.generated Sun Mar 14 07:52:10 CST 2021
     */
    PerIndicatorprize selectByPrimaryKey(Integer indicatorprizeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPrize
     *
     * @mbg.generated Sun Mar 14 07:52:10 CST 2021
     */
    List<PerIndicatorprize> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPrize
     *
     * @mbg.generated Sun Mar 14 07:52:10 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorprize record);
}