package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIncome;

import java.math.BigDecimal;
import java.util.List;

public interface PerIncomeMapper {

    List<PerIncome> selectPerIncome(PerIncome record);

    PerIncome selectPerIncomeById(Integer incomeid);

    BigDecimal selectPerIncomeCaculateTotal(PerIncome record);

    int insertPerIncome(PerIncome record);

    int updatePerIncome(PerIncome record);

    int updatePerIncomeConfirmById(Integer incomeid);

    int updatePerIncomeDeletedById(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    PerIncome selectByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    List<PerIncome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    int updateByPrimaryKey(PerIncome record);
}