package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorfund;
import java.util.List;

public interface PerIndicatorfundMapper {

    PerIndicatorfund selectPerIndicatorfundById(Integer indicatorfundid);

    int updatePerIndicatorfund(PerIndicatorfund record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorFund
     *
     * @mbg.generated Sat Mar 13 15:50:08 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatorfundid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorFund
     *
     * @mbg.generated Sat Mar 13 15:50:08 CST 2021
     */
    int insert(PerIndicatorfund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorFund
     *
     * @mbg.generated Sat Mar 13 15:50:08 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorFund
     *
     * @mbg.generated Sat Mar 13 15:50:08 CST 2021
     */
    List<PerIndicatorfund> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorFund
     *
     * @mbg.generated Sat Mar 13 15:50:08 CST 2021
     */

}