package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorproduct;
import java.util.List;

public interface PerIndicatorproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorProduct
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatorproductid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorProduct
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    int insert(PerIndicatorproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorProduct
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    PerIndicatorproduct selectByPrimaryKey(Integer indicatorproductid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorProduct
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    List<PerIndicatorproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorProduct
     *
     * @mbg.generated Sun Mar 14 20:57:34 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorproduct record);
}