package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorsoftware;
import java.util.List;

public interface PerIndicatorsoftwareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorSoftware
     *
     * @mbg.generated Sun Mar 14 20:57:10 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatorsoftwareid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorSoftware
     *
     * @mbg.generated Sun Mar 14 20:57:10 CST 2021
     */
    int insert(PerIndicatorsoftware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorSoftware
     *
     * @mbg.generated Sun Mar 14 20:57:10 CST 2021
     */
    PerIndicatorsoftware selectByPrimaryKey(Integer indicatorsoftwareid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorSoftware
     *
     * @mbg.generated Sun Mar 14 20:57:10 CST 2021
     */
    List<PerIndicatorsoftware> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorSoftware
     *
     * @mbg.generated Sun Mar 14 20:57:11 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorsoftware record);
}