package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorthesis;
import java.util.List;

public interface PerIndicatorthesisMapper {

    PerIndicatorthesis selectPerIndicatorthesisById(Integer indicatorthesisid);

    List<PerIndicatorthesis> selectPerIndicatorthesis(PerIndicatorthesis record);

    int updatePerIndicatorthesis(PerIndicatorthesis record);

    int deleteByPrimaryKey(Integer indicatorthesisid);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorThesis
     *
     * @mbg.generated Sun Mar 14 20:55:54 CST 2021
     */
    int insert(PerIndicatorthesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorThesis
     *
     * @mbg.generated Sun Mar 14 20:55:54 CST 2021
     */
    PerIndicatorthesis selectByPrimaryKey(Integer indicatorthesisid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorThesis
     *
     * @mbg.generated Sun Mar 14 20:55:54 CST 2021
     */
    List<PerIndicatorthesis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorThesis
     *
     * @mbg.generated Sun Mar 14 20:55:54 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorthesis record);
}