package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorstandard;
import java.util.List;

public interface PerIndicatorstandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorStandard
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatorstandardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorStandard
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    int insert(PerIndicatorstandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorStandard
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    PerIndicatorstandard selectByPrimaryKey(Integer indicatorstandardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorStandard
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    List<PerIndicatorstandard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorStandard
     *
     * @mbg.generated Sun Mar 14 20:56:19 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorstandard record);
}