package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIncome;
import java.util.List;

public interface PerIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    int deleteByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    int insert(PerIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    PerIncome selectByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    List<PerIncome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Income
     *
     * @mbg.generated Fri Mar 26 15:12:59 CST 2021
     */
    int updateByPrimaryKey(PerIncome record);
}