package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatortech;
import java.util.List;

public interface PerIndicatortechMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorTech
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatortechid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorTech
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    int insert(PerIndicatortech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorTech
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    PerIndicatortech selectByPrimaryKey(Integer indicatortechid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorTech
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    List<PerIndicatortech> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorTech
     *
     * @mbg.generated Sun Mar 14 20:59:12 CST 2021
     */
    int updateByPrimaryKey(PerIndicatortech record);
}