package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatororderrate;
import java.util.List;

public interface PerIndicatororderrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorOrderRate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    int deleteByPrimaryKey(Integer indicatororderrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorOrderRate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    int insert(PerIndicatororderrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorOrderRate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    PerIndicatororderrate selectByPrimaryKey(Integer indicatororderrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorOrderRate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    List<PerIndicatororderrate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorOrderRate
     *
     * @mbg.generated Sun Mar 14 20:58:26 CST 2021
     */
    int updateByPrimaryKey(PerIndicatororderrate record);
}