package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorarticle;

import java.util.List;

public interface PerIndicatorarticleMapper {

    List<PerIndicatorarticle> selectPerIndicatorarticle(PerIndicatorarticle record);
    int updatePerIndicatorarticle(PerIndicatorarticle record);

    int deleteByPrimaryKey(Integer indicatorarticleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorArticle
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    int insert(PerIndicatorarticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorArticle
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    PerIndicatorarticle selectByPrimaryKey(Integer indicatorarticleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorArticle
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    List<PerIndicatorarticle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorArticle
     *
     * @mbg.generated Sun Mar 14 20:56:40 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorarticle record);
}