package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicator;
import java.util.List;

public interface PerIndicatorMapper {

    List<PerIndicator> selectPerIndicator(PerIndicator record);
    int insertPerIndicator(PerIndicator record);

    List<PerIndicator> selectPerIndicatorTree();

    int deleteByPrimaryKey(Integer indicatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Indicator
     *
     * @mbg.generated Sat Mar 13 07:31:30 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Indicator
     *
     * @mbg.generated Sat Mar 13 07:31:30 CST 2021
     */
    PerIndicator selectByPrimaryKey(Integer indicatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Indicator
     *
     * @mbg.generated Sat Mar 13 07:31:30 CST 2021
     */
    List<PerIndicator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_Indicator
     *
     * @mbg.generated Sat Mar 13 07:31:30 CST 2021
     */
    int updateByPrimaryKey(PerIndicator record);
}