package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerIndicatorpatent;
import java.util.List;

public interface PerIndicatorpatentMapper {

    List<PerIndicatorpatent> selectPerIndicatorpatent(PerIndicatorpatent record);
    int updatePerIndicatorpatent(PerIndicatorpatent record);
    int insertPerIndicatorpatent(PerIndicatorpatent record);

    int deleteByPrimaryKey(Integer indicatorpatentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPatent
     *
     * @mbg.generated Sun Mar 14 19:41:04 CST 2021
     */
    int insert(PerIndicatorpatent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPatent
     *
     * @mbg.generated Sun Mar 14 19:41:04 CST 2021
     */
    PerIndicatorpatent selectByPrimaryKey(Integer indicatorpatentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPatent
     *
     * @mbg.generated Sun Mar 14 19:41:04 CST 2021
     */
    List<PerIndicatorpatent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_IndicatorPatent
     *
     * @mbg.generated Sun Mar 14 19:41:04 CST 2021
     */
    int updateByPrimaryKey(PerIndicatorpatent record);
}