package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerScoreschangelog;
import java.util.List;

public interface PerScoreschangelogMapper {


    List<PerScoreschangelog> selectPerScoreschangelog(PerScoreschangelog record);

    int insertPerScoreschangelog(PerScoreschangelog record);


    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ScoresChangeLog
     *
     * @mbg.generated Tue Mar 16 13:30:21 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ScoresChangeLog
     *
     * @mbg.generated Tue Mar 16 13:30:21 CST 2021
     */
    PerScoreschangelog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ScoresChangeLog
     *
     * @mbg.generated Tue Mar 16 13:30:21 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_ScoresChangeLog
     *
     * @mbg.generated Tue Mar 16 13:30:21 CST 2021
     */
    int updateByPrimaryKey(PerScoreschangelog record);
}