package com.ruoyi.performance.mapper;

import com.ruoyi.performance.domain.PerTeamperformance;
import java.util.List;

public interface PerTeamperformanceMapper {


    int updatePerTeamperformance(PerTeamperformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_TeamPerformance
     *
     * @mbg.generated Sat Mar 13 07:36:51 CST 2021
     */
    int deleteByPrimaryKey(Integer performanceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_TeamPerformance
     *
     * @mbg.generated Sat Mar 13 07:36:51 CST 2021
     */
    int insert(PerTeamperformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_TeamPerformance
     *
     * @mbg.generated Sat Mar 13 07:36:51 CST 2021
     */
    PerTeamperformance selectByPrimaryKey(Integer performanceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_TeamPerformance
     *
     * @mbg.generated Sat Mar 13 07:36:51 CST 2021
     */
    List<PerTeamperformance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PER_TeamPerformance
     *
     * @mbg.generated Sat Mar 13 07:36:51 CST 2021
     */
    int updateByPrimaryKey(PerTeamperformance record);
}