package com.ruoyi.fourtech.mapper;

import com.ruoyi.contract.domain.AudContract;
import com.ruoyi.fourtech.domain.AudFourtech;
import java.util.List;

public interface AudFourtechMapper {

    List<AudFourtech> selectFourtechTijiaorenByUserid(Integer userid);
    List<AudFourtech> selectFourtechTijiaoren(AudFourtech record);
    AudFourtech selectFourtechById(Integer fourtechid);

    int deleteByPrimaryKey(Integer fourtechid);

    int insertFourtech(AudFourtech record);

    int updateFourtech(AudFourtech record);

    int updateFourtechStatus(AudFourtech record);


    List<AudFourtech> selectFourtechChushen(AudFourtech record);
    List<AudFourtech> selectFourtechXiangmu(AudFourtech record);
    List<AudFourtech> selectFourtechBumen(AudFourtech record);
    List<AudFourtech> selectFourtechChu(AudFourtech record);
    List<AudFourtech> selectFourtechSuozhang(AudFourtech record);

    List<AudFourtech> selectFourtechAuditedByUserid(Integer userid);

    List<AudFourtech> selectFourtechShenPiWanCheng(AudFourtech record);

    int updateFourtechCode(AudFourtech record);

    List<AudFourtech> queryFourtech(AudFourtech record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    AudFourtech selectByPrimaryKey(Integer fourtechid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    List<AudFourtech> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    int updateByPrimaryKey(AudFourtech record);
}