package com.ruoyi.fourtech.mapper;

import com.ruoyi.fourtech.domain.AudFourtech;
import java.util.List;

public interface AudFourtechMapper {

    List<AudFourtech> selectFourtechTijiaorenByUserid(Integer userid);
    List<AudFourtech> selectFourtechTijiaoren(AudFourtech record);
    AudFourtech selectFourtechById(Integer fourtechid);

    int deleteByPrimaryKey(Integer fourtechid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    int insert(AudFourtech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    AudFourtech selectByPrimaryKey(Integer fourtechid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    List<AudFourtech> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_FourTech
     *
     * @mbg.generated Wed Feb 24 14:42:05 CST 2021
     */
    int updateByPrimaryKey(AudFourtech record);
}