package com.ruoyi.sku.mapper;

import com.ruoyi.sku.domain.SkuExport;
import java.util.List;

public interface SkuExportMapper {

    int insertSkuExport(SkuExport record);

    int updateSkuExportStatus1(SkuExport record);


    List<SkuExport> selectSkuExport(SkuExport record);

    SkuExport selectSkuExportById(Long exportId);

    int deleteSkuExportByExportIds(List<Long> exportIds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    SkuExport selectByPrimaryKey(Long exportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    int updateByPrimaryKey(SkuExport record);
}