package com.ruoyi.sku.mapper;

import com.ruoyi.sku.domain.SkuExport;
import java.util.List;

public interface SkuExportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    int deleteByPrimaryKey(Long exportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    int insert(SkuExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    SkuExport selectByPrimaryKey(Long exportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    List<SkuExport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_export
     *
     * @mbg.generated Sun Jul 04 08:52:36 CST 2021
     */
    int updateByPrimaryKey(SkuExport record);
}