package com.ruoyi.sku.mapper;

import com.ruoyi.sku.domain.SkuPhoto;
import java.util.List;

public interface SkuPhotoMapper {

    List<SkuPhoto> selectSkuPhoto(SkuPhoto record);

    int insertSkuPhoto(SkuPhoto record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_photo
     *
     * @mbg.generated Sun Jul 04 14:36:15 CST 2021
     */
    int deleteByPrimaryKey(Long photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_photo
     *
     * @mbg.generated Sun Jul 04 14:36:15 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_photo
     *
     * @mbg.generated Sun Jul 04 14:36:15 CST 2021
     */
    SkuPhoto selectByPrimaryKey(Long photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_photo
     *
     * @mbg.generated Sun Jul 04 14:36:15 CST 2021
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_photo
     *
     * @mbg.generated Sun Jul 04 14:36:15 CST 2021
     */
    int updateByPrimaryKey(SkuPhoto record);
}