package com.ruoyi.logis.domain;

import java.util.Date;

public class LogisContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.contract_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private Long contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.user_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.constract_no
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private String constractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.contract_name
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.contract_file
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private String contractFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.status
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logis_contract.created
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.contract_id
     *
     * @return the value of logis_contract.contract_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.contract_id
     *
     * @param contractId the value for logis_contract.contract_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.user_id
     *
     * @return the value of logis_contract.user_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.user_id
     *
     * @param userId the value for logis_contract.user_id
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.constract_no
     *
     * @return the value of logis_contract.constract_no
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public String getConstractNo() {
        return constractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.constract_no
     *
     * @param constractNo the value for logis_contract.constract_no
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setConstractNo(String constractNo) {
        this.constractNo = constractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.contract_name
     *
     * @return the value of logis_contract.contract_name
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.contract_name
     *
     * @param contractName the value for logis_contract.contract_name
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.contract_file
     *
     * @return the value of logis_contract.contract_file
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public String getContractFile() {
        return contractFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.contract_file
     *
     * @param contractFile the value for logis_contract.contract_file
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setContractFile(String contractFile) {
        this.contractFile = contractFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.status
     *
     * @return the value of logis_contract.status
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.status
     *
     * @param status the value for logis_contract.status
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logis_contract.created
     *
     * @return the value of logis_contract.created
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logis_contract.created
     *
     * @param created the value for logis_contract.created
     *
     * @mbg.generated Sat Jan 09 15:38:35 CST 2021
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}