package com.ruoyi.expense.domain;

import com.ruoyi.common.core.domain.BaseEntity;

import java.math.BigDecimal;

public class AudExpense extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.ExpenseSheetID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer expensesheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.ExpenseName
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String expensename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.ExpenseSheetCode
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String expensesheetcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.SheetUserID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer sheetuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.SheetTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String sheettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.ProjectID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.OrganizationID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer organizationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.Money
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.daxie
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String daxie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.Reason
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.VoucherCount
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer vouchercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.PassTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private String passtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Expense.SheetStatus
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    private Integer sheetstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.ExpenseSheetID
     *
     * @return the value of Aud_Expense.ExpenseSheetID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getExpensesheetid() {
        return expensesheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.ExpenseSheetID
     *
     * @param expensesheetid the value for Aud_Expense.ExpenseSheetID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setExpensesheetid(Integer expensesheetid) {
        this.expensesheetid = expensesheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.ExpenseName
     *
     * @return the value of Aud_Expense.ExpenseName
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getExpensename() {
        return expensename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.ExpenseName
     *
     * @param expensename the value for Aud_Expense.ExpenseName
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setExpensename(String expensename) {
        this.expensename = expensename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.ExpenseSheetCode
     *
     * @return the value of Aud_Expense.ExpenseSheetCode
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getExpensesheetcode() {
        return expensesheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.ExpenseSheetCode
     *
     * @param expensesheetcode the value for Aud_Expense.ExpenseSheetCode
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setExpensesheetcode(String expensesheetcode) {
        this.expensesheetcode = expensesheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.SheetUserID
     *
     * @return the value of Aud_Expense.SheetUserID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getSheetuserid() {
        return sheetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.SheetUserID
     *
     * @param sheetuserid the value for Aud_Expense.SheetUserID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setSheetuserid(Integer sheetuserid) {
        this.sheetuserid = sheetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.SheetTime
     *
     * @return the value of Aud_Expense.SheetTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getSheettime() {
        return sheettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.SheetTime
     *
     * @param sheettime the value for Aud_Expense.SheetTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setSheettime(String sheettime) {
        this.sheettime = sheettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.ProjectID
     *
     * @return the value of Aud_Expense.ProjectID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.ProjectID
     *
     * @param projectid the value for Aud_Expense.ProjectID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.OrganizationID
     *
     * @return the value of Aud_Expense.OrganizationID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.OrganizationID
     *
     * @param organizationid the value for Aud_Expense.OrganizationID
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setOrganizationid(Integer organizationid) {
        this.organizationid = organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.Money
     *
     * @return the value of Aud_Expense.Money
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.Money
     *
     * @param money the value for Aud_Expense.Money
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.daxie
     *
     * @return the value of Aud_Expense.daxie
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getDaxie() {
        return daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.daxie
     *
     * @param daxie the value for Aud_Expense.daxie
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setDaxie(String daxie) {
        this.daxie = daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.Reason
     *
     * @return the value of Aud_Expense.Reason
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.Reason
     *
     * @param reason the value for Aud_Expense.Reason
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.VoucherCount
     *
     * @return the value of Aud_Expense.VoucherCount
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getVouchercount() {
        return vouchercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.VoucherCount
     *
     * @param vouchercount the value for Aud_Expense.VoucherCount
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setVouchercount(Integer vouchercount) {
        this.vouchercount = vouchercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.PassTime
     *
     * @return the value of Aud_Expense.PassTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public String getPasstime() {
        return passtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.PassTime
     *
     * @param passtime the value for Aud_Expense.PassTime
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setPasstime(String passtime) {
        this.passtime = passtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Expense.SheetStatus
     *
     * @return the value of Aud_Expense.SheetStatus
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public Integer getSheetstatus() {
        return sheetstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Expense.SheetStatus
     *
     * @param sheetstatus the value for Aud_Expense.SheetStatus
     *
     * @mbg.generated Sun Feb 21 22:08:20 CST 2021
     */
    public void setSheetstatus(Integer sheetstatus) {
        this.sheetstatus = sheetstatus;
    }
}