package com.ruoyi.sheet.mapper;

import com.ruoyi.sheet.domain.AudSheet;
import java.util.List;

public interface AudSheetMapper {


    List<AudSheet> selectSheetTijiaorenByUserid(Integer userid);
    
    int deleteByPrimaryKey(Integer sheetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Sheet
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    int insert(AudSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Sheet
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    AudSheet selectByPrimaryKey(Integer sheetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Sheet
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    List<AudSheet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Sheet
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    int updateByPrimaryKey(AudSheet record);
}