package com.ruoyi.project.mapper;

import com.ruoyi.project.domain.AudProject;


import java.util.List;

public interface AudProjectMapper {

    List<AudProject> selectAudProjectList(AudProject project);

    int deleteByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Project
     *
     * @mbg.generated Mon Jan 25 16:18:51 CST 2021
     */
    int insert(AudProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Project
     *
     * @mbg.generated Mon Jan 25 16:18:51 CST 2021
     */
    AudProject selectByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Project
     *
     * @mbg.generated Mon Jan 25 16:18:51 CST 2021
     */
    List<AudProject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_Project
     *
     * @mbg.generated Mon Jan 25 16:18:51 CST 2021
     */
    int updateByPrimaryKey(AudProject record);
}