package com.ruoyi.project.mapper;

import com.ruoyi.project.domain.AudProjectdoc;
import java.util.List;

public interface AudProjectdocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_ProjectDoc
     *
     * @mbg.generated Wed Jan 27 17:38:34 CST 2021
     */
    int insert(AudProjectdoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Aud_ProjectDoc
     *
     * @mbg.generated Wed Jan 27 17:38:34 CST 2021
     */
    List<AudProjectdoc> selectAll();
}