package com.ruoyi.project.mapper;

import com.ruoyi.project.domain.PmProjectmember;
import java.util.List;

public interface PmProjectmemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ProjectMember
     *
     * @mbg.generated Wed Jan 27 15:14:03 CST 2021
     */
    int insert(PmProjectmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ProjectMember
     *
     * @mbg.generated Wed Jan 27 15:14:03 CST 2021
     */
    List<PmProjectmember> selectAll();
}