package com.ruoyi.sheet.domain;

import java.math.BigDecimal;

public class AudSheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer sheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetCode
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String sheetcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetType
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String sheettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.RelatedContractID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer relatedcontractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.ThisPayTimes
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String thispaytimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer sheetuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String sheettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.ProjectID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.OrganizationID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer organizationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.heji_zong
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private BigDecimal hejiZong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.heji_xiaoji
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private BigDecimal hejiXiaoji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.heji_yiqian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private BigDecimal hejiYiqian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.heji_bennian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private BigDecimal hejiBennian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.heji_benci
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private BigDecimal hejiBenci;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.daxie
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String daxie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.ReferenceID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String referenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.Reason
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.PayConfirmTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private String payconfirmtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.PayConfirmUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer payconfirmuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Aud_Sheet.SheetStatus
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    private Integer sheetstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetID
     *
     * @return the value of Aud_Sheet.SheetID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetID
     *
     * @param sheetid the value for Aud_Sheet.SheetID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheetid(Integer sheetid) {
        this.sheetid = sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetCode
     *
     * @return the value of Aud_Sheet.SheetCode
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getSheetcode() {
        return sheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetCode
     *
     * @param sheetcode the value for Aud_Sheet.SheetCode
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheetcode(String sheetcode) {
        this.sheetcode = sheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetType
     *
     * @return the value of Aud_Sheet.SheetType
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getSheettype() {
        return sheettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetType
     *
     * @param sheettype the value for Aud_Sheet.SheetType
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheettype(String sheettype) {
        this.sheettype = sheettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.RelatedContractID
     *
     * @return the value of Aud_Sheet.RelatedContractID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getRelatedcontractid() {
        return relatedcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.RelatedContractID
     *
     * @param relatedcontractid the value for Aud_Sheet.RelatedContractID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setRelatedcontractid(Integer relatedcontractid) {
        this.relatedcontractid = relatedcontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.ThisPayTimes
     *
     * @return the value of Aud_Sheet.ThisPayTimes
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getThispaytimes() {
        return thispaytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.ThisPayTimes
     *
     * @param thispaytimes the value for Aud_Sheet.ThisPayTimes
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setThispaytimes(String thispaytimes) {
        this.thispaytimes = thispaytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetUserID
     *
     * @return the value of Aud_Sheet.SheetUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getSheetuserid() {
        return sheetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetUserID
     *
     * @param sheetuserid the value for Aud_Sheet.SheetUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheetuserid(Integer sheetuserid) {
        this.sheetuserid = sheetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetTime
     *
     * @return the value of Aud_Sheet.SheetTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getSheettime() {
        return sheettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetTime
     *
     * @param sheettime the value for Aud_Sheet.SheetTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheettime(String sheettime) {
        this.sheettime = sheettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.ProjectID
     *
     * @return the value of Aud_Sheet.ProjectID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.ProjectID
     *
     * @param projectid the value for Aud_Sheet.ProjectID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.OrganizationID
     *
     * @return the value of Aud_Sheet.OrganizationID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.OrganizationID
     *
     * @param organizationid the value for Aud_Sheet.OrganizationID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setOrganizationid(Integer organizationid) {
        this.organizationid = organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.heji_zong
     *
     * @return the value of Aud_Sheet.heji_zong
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public BigDecimal getHejiZong() {
        return hejiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.heji_zong
     *
     * @param hejiZong the value for Aud_Sheet.heji_zong
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setHejiZong(BigDecimal hejiZong) {
        this.hejiZong = hejiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.heji_xiaoji
     *
     * @return the value of Aud_Sheet.heji_xiaoji
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public BigDecimal getHejiXiaoji() {
        return hejiXiaoji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.heji_xiaoji
     *
     * @param hejiXiaoji the value for Aud_Sheet.heji_xiaoji
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setHejiXiaoji(BigDecimal hejiXiaoji) {
        this.hejiXiaoji = hejiXiaoji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.heji_yiqian
     *
     * @return the value of Aud_Sheet.heji_yiqian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public BigDecimal getHejiYiqian() {
        return hejiYiqian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.heji_yiqian
     *
     * @param hejiYiqian the value for Aud_Sheet.heji_yiqian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setHejiYiqian(BigDecimal hejiYiqian) {
        this.hejiYiqian = hejiYiqian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.heji_bennian
     *
     * @return the value of Aud_Sheet.heji_bennian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public BigDecimal getHejiBennian() {
        return hejiBennian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.heji_bennian
     *
     * @param hejiBennian the value for Aud_Sheet.heji_bennian
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setHejiBennian(BigDecimal hejiBennian) {
        this.hejiBennian = hejiBennian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.heji_benci
     *
     * @return the value of Aud_Sheet.heji_benci
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public BigDecimal getHejiBenci() {
        return hejiBenci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.heji_benci
     *
     * @param hejiBenci the value for Aud_Sheet.heji_benci
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setHejiBenci(BigDecimal hejiBenci) {
        this.hejiBenci = hejiBenci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.daxie
     *
     * @return the value of Aud_Sheet.daxie
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getDaxie() {
        return daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.daxie
     *
     * @param daxie the value for Aud_Sheet.daxie
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setDaxie(String daxie) {
        this.daxie = daxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.ReferenceID
     *
     * @return the value of Aud_Sheet.ReferenceID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getReferenceid() {
        return referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.ReferenceID
     *
     * @param referenceid the value for Aud_Sheet.ReferenceID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.Reason
     *
     * @return the value of Aud_Sheet.Reason
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.Reason
     *
     * @param reason the value for Aud_Sheet.Reason
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.PayConfirmTime
     *
     * @return the value of Aud_Sheet.PayConfirmTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public String getPayconfirmtime() {
        return payconfirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.PayConfirmTime
     *
     * @param payconfirmtime the value for Aud_Sheet.PayConfirmTime
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setPayconfirmtime(String payconfirmtime) {
        this.payconfirmtime = payconfirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.PayConfirmUserID
     *
     * @return the value of Aud_Sheet.PayConfirmUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getPayconfirmuserid() {
        return payconfirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.PayConfirmUserID
     *
     * @param payconfirmuserid the value for Aud_Sheet.PayConfirmUserID
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setPayconfirmuserid(Integer payconfirmuserid) {
        this.payconfirmuserid = payconfirmuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Aud_Sheet.SheetStatus
     *
     * @return the value of Aud_Sheet.SheetStatus
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public Integer getSheetstatus() {
        return sheetstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Aud_Sheet.SheetStatus
     *
     * @param sheetstatus the value for Aud_Sheet.SheetStatus
     *
     * @mbg.generated Thu Feb 11 20:45:13 CST 2021
     */
    public void setSheetstatus(Integer sheetstatus) {
        this.sheetstatus = sheetstatus;
    }
}