package com.ruoyi.sheet.domain;

public class BasUsedmaxserialnumber {

    private String modulename;

    private Integer usedmaxserialnumber;
    private String somedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_UsedMaxSerialNumber.ModuleName
     *
     * @return the value of BAS_UsedMaxSerialNumber.ModuleName
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_UsedMaxSerialNumber.ModuleName
     *
     * @param modulename the value for BAS_UsedMaxSerialNumber.ModuleName
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_UsedMaxSerialNumber.UsedMaxSerialNumber
     *
     * @return the value of BAS_UsedMaxSerialNumber.UsedMaxSerialNumber
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public Integer getUsedmaxserialnumber() {
        return usedmaxserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_UsedMaxSerialNumber.UsedMaxSerialNumber
     *
     * @param usedmaxserialnumber the value for BAS_UsedMaxSerialNumber.UsedMaxSerialNumber
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public void setUsedmaxserialnumber(Integer usedmaxserialnumber) {
        this.usedmaxserialnumber = usedmaxserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_UsedMaxSerialNumber.SomeDate
     *
     * @return the value of BAS_UsedMaxSerialNumber.SomeDate
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public String getSomedate() {
        return somedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_UsedMaxSerialNumber.SomeDate
     *
     * @param somedate the value for BAS_UsedMaxSerialNumber.SomeDate
     *
     * @mbg.generated Wed Feb 17 17:09:07 CST 2021
     */
    public void setSomedate(String somedate) {
        this.somedate = somedate;
    }
}